from __future__ import annotations

CANONICAL_SOURCE_SHA256 = "ea173d7fa92698375b1472a84030b5c8ee05a5463a915cc8f3995ebf0b7fe1c8"
GROOVY_RESOURCE_SHA256 = "4bb3d078a020729b1c91f647fcf0bceb12c3b8595d10f6ef37c014a18489df97"
PROCESSES_TRIM_RESOURCE_SHA256 = "99109296aed706167baabe69f36e455d11f9ea368ccc0bc6b9483a896a328cf7"
MODULE_ORDER = (
    "startup.py",
    "data_structures.py",
    "settings.py",
    "run_state.py",
    "command_line.py",
    "images/channel_files.py",
    "workspace/folder_checks.py",
    "images/image_loading.py",
    "images/image_processing.py",
    "segmentation/candidate_features.py",
    "segmentation/cellpose_segmentation.py",
    "nuclei/dapi_nuclei.py",
    "nuclei/dapi_3d_inventory.py",
    "segmentation/candidate_evaluation.py",
    "segmentation/measurement_channel_qc.py",
    "segmentation/z_position_quality.py",
    "compartments/compartment_validation.py",
    "compartments/cell_separation.py",
    "nuclei/nucleus_ownership.py",
    "compartments/soma_completion.py",
    "compartments/soma_and_processes.py",
    "analysis_modes/structural_fluorescence.py",
    "segmentation/candidate_selection.py",
    "segmentation/standard_morphology_candidates.py",
    "segmentation/structural_refinement_candidates.py",
    "segmentation/candidate_catalog.py",
    "segmentation/distributional_threshold_candidates.py",
    "reporting/analysis_report.py",
    "fiji_review/fiji_launcher.py",
    "fiji_review/review_protocol.py",
    "reporting/excel_results.py",
    "workspace/result_publishing.py",
    "analysis_controller.py",
)
REQUIRED_RUNTIME_SYMBOLS = (
    "_main_locked",
    "build_dapi_object_inventory_3d",
    "complete_candidate_specs",
    "launch_fiji_workflow",
    "main",
    "inspect_measurement_channel_windows",
    "plan_fixed_z_windows",
    "prepare_fiji_runtime",
    "publish_output_bundle",
    "rank_position_production_candidates",
    "run_cellpose_mask",
    "score_z_position_best_candidates",
    "split_astrocyte_compartments_for_profile",
)
