from __future__ import annotations

CANONICAL_SOURCE_SHA256 = "d55834a97baac6d01fafdc5bbe6905dffec6067af8016cb1b2bdd53d4953143c"
GROOVY_RESOURCE_SHA256 = "f5fb02810fb2564d8df7445e06f433904cd97fb5fe2da7df6e6f5aa6a0366d20"
MODULE_ORDER = (
    "startup.py",
    "data_structures.py",
    "settings.py",
    "run_state.py",
    "command_line.py",
    "images/channel_files.py",
    "workspace/folder_checks.py",
    "images/image_loading.py",
    "images/image_processing.py",
    "segmentation/candidate_features.py",
    "segmentation/cellpose_segmentation.py",
    "nuclei/dapi_nuclei.py",
    "nuclei/dapi_3d_inventory.py",
    "segmentation/candidate_evaluation.py",
    "compartments/compartment_validation.py",
    "compartments/cell_separation.py",
    "nuclei/nucleus_ownership.py",
    "compartments/soma_completion.py",
    "compartments/soma_and_processes.py",
    "analysis_modes/structural_fluorescence.py",
    "segmentation/candidate_selection.py",
    "segmentation/standard_morphology_candidates.py",
    "segmentation/structural_refinement_candidates.py",
    "segmentation/candidate_catalog.py",
    "segmentation/distributional_threshold_candidates.py",
    "reporting/analysis_report.py",
    "fiji_review/fiji_launcher.py",
    "fiji_review/review_protocol.py",
    "reporting/excel_results.py",
    "workspace/result_publishing.py",
    "analysis_controller.py",
)
REQUIRED_RUNTIME_SYMBOLS = (
    "_main_locked",
    "build_dapi_object_inventory_3d",
    "complete_candidate_specs",
    "launch_fiji_workflow",
    "main",
    "prepare_fiji_runtime",
    "publish_output_bundle",
    "rank_complete_production_candidates",
    "run_cellpose_mask",
    "split_astrocyte_compartments_for_profile",
)
